language: node_js
node_js:
  - '12'
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &
services:
  - mongodb
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
