language: node_js
node_js:
  - '12'
dist: trusty
services:
  - mongodb
  - redis-server
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run heroku-postbuild
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
