const QuestionActionTypes = {
  HANDLE_SEARCH_CHANGE: 'HANDLE_SEARCH_CHANGE',
  SET_QUESTION_DATA: 'SET_QUESTION_DATA',
  SET_CURRENT_MODULE: 'SET_CURRENT_MODULE',
  FETCH_START: 'FETCH_START',
  FETCH_FAILURE: 'FETCH_FAILURE',
  FETCH_SUCCCESS: 'FETCH_SUCCCESS',
  POST_START: 'POST_START',
  POST_FAILURE: 'POST_FAILURE',
  POST_SUCCESS: 'POST_SUCCESS',
  DELETION_START: 'DELETION_START',
  DELETION_SUCCESS: 'DELETION_SUCCESS',
  DELETION_FAILURE: 'DELETION_FAILURE',
};

export default QuestionActionTypes;
