const QuestionActionTypes = {
  HANDLE_SEARCH_CHANGE: 'HANDLE_SEARCH_CHANGE',
  SET_QUESTION_DATA: 'SET_QUESTION_DATA',
  SET_CURRENT_MODULE: 'SET_CURRENT_MODULE',
  FETCH_START: 'FETCH_START',
  FETCH_FAILURE: 'FETCH_FAILURE',
};

export default QuestionActionTypes;
